### ISSUE TITLE
api 논의.

### ISSUE THREAD

**Issue by zeakd** [sparcs-kaist/apply_sparcs#4]
json파일로 스펙을 만들면 서로 공유하기 좋을 것같다.

**Comment by samjo-nyang** [comment]
https://apiary.io/: 공짜는 private이 안되기는 하지만 쓸만하다고 들었습니당

**Comment by zeakd** [comment]
얘기해봤는데 지금은 rest api자체가 필요한 부분이 없더라고 ㅋㅋㅋ

**Comment by zeakd** [comment]
아직은 필요한 부분이 없어서 닫습니다
